In [1]:
import torch 
from torchvision import models 

In [2]:
torch.ones(10)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
torch.zeros(10)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
torch.ones((2,5))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [5]:
torch.ones((3,5))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [6]:
z = torch.zeros((3,5))

In [7]:
z.shape

torch.Size([3, 5])

In [8]:
z[1:, :]

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [9]:
wait = torch.randint(0,10,(5,5),dtype = torch.float32)

In [10]:
wait 

tensor([[9., 1., 1., 7., 2.],
        [3., 6., 6., 9., 3.],
        [9., 3., 9., 4., 7.],
        [8., 2., 0., 4., 5.],
        [0., 4., 4., 3., 7.]])

In [11]:
wait[1:, 1:]

tensor([[6., 6., 9., 3.],
        [3., 9., 4., 7.],
        [2., 0., 4., 5.],
        [4., 4., 3., 7.]])

In [12]:
wait[3:, 0]

tensor([8., 0.])

In [13]:
torch.randn(3,4,5) # channels , rows, columns 

tensor([[[ 1.0800, -1.0363, -0.2134,  1.7335, -0.6182],
         [ 0.8326,  1.2203,  0.9697,  0.2248, -0.7992],
         [ 0.8559,  0.0674,  0.9632,  0.0359,  0.3953],
         [ 2.1441, -0.6537,  0.4777, -0.0943,  0.8233]],

        [[-0.3395, -0.4890,  0.4603, -0.0815,  1.2766],
         [-1.0230,  2.9410,  0.1326,  0.9120,  0.0458],
         [-0.1175, -0.9099, -0.6435, -0.6929, -0.4960],
         [ 0.0947,  0.2560,  1.3297,  0.6208, -0.2756]],

        [[-0.8124,  0.8454,  0.8470,  1.3834, -0.1195],
         [-0.5869,  1.3541, -0.5919,  0.4630, -0.8565],
         [ 0.5551, -0.2565, -1.4186,  1.0915, -0.2431],
         [ 0.7785,  0.2294,  1.3218, -1.0336, -1.1087]]])

In [14]:
torch.randn(1,3,5,5) # batch , channels, rows, columns 

tensor([[[[-0.5585,  0.6944,  0.5026, -0.5080,  0.3340],
          [ 0.0714,  1.3269, -0.1472, -0.5579, -0.3222],
          [ 0.4198, -0.5404, -1.3409, -1.3523, -0.1582],
          [ 1.0525, -1.8720,  0.6526,  0.1949, -0.0764],
          [-1.4627, -0.0310, -1.7442,  0.6025, -1.2766]],

         [[ 0.7472, -0.7741,  0.2923,  0.3943, -1.2387],
          [-0.7695,  1.2783,  1.3001, -0.8214, -0.9262],
          [ 0.6591,  0.3165,  0.8561, -1.1057, -0.0397],
          [-0.2077,  0.5183, -0.1992,  0.7092, -0.3960],
          [-0.3380, -0.1620, -1.1149,  1.7339,  0.2553]],

         [[ 0.8439,  1.7550, -0.9276, -0.5444,  0.9512],
          [ 0.1983,  0.6564,  2.5738, -1.9805,  1.0597],
          [ 0.7932,  1.6373,  1.1402,  0.7216,  1.2134],
          [ 1.7417, -0.7589, -0.1570,  1.2332, -0.5655],
          [ 0.4805, -0.9030, -0.1133, -0.9717,  0.1567]]]])

In [15]:
wait, wait.shape

(tensor([[9., 1., 1., 7., 2.],
         [3., 6., 6., 9., 3.],
         [9., 3., 9., 4., 7.],
         [8., 2., 0., 4., 5.],
         [0., 4., 4., 3., 7.]]), torch.Size([5, 5]))

In [16]:
torch.unsqueeze(wait, -2 ),torch.unsqueeze(wait, 2 ) # adding dimension rowwise and adding dimeension to each element in the row with adding it rowwise also :)

(tensor([[[9., 1., 1., 7., 2.]],
 
         [[3., 6., 6., 9., 3.]],
 
         [[9., 3., 9., 4., 7.]],
 
         [[8., 2., 0., 4., 5.]],
 
         [[0., 4., 4., 3., 7.]]]), tensor([[[9.],
          [1.],
          [1.],
          [7.],
          [2.]],
 
         [[3.],
          [6.],
          [6.],
          [9.],
          [3.]],
 
         [[9.],
          [3.],
          [9.],
          [4.],
          [7.]],
 
         [[8.],
          [2.],
          [0.],
          [4.],
          [5.]],
 
         [[0.],
          [4.],
          [4.],
          [3.],
          [7.]]]))

# types of arguments 

*  torch.float32 or torch.float : 32-bit floating-point
*  torch.float64 or torch.double : 64-bit, double-precision floating-point
*  torch.float16 or torch.half : 16-bit, half-precision floating-point
*  torch.int8 : signed 8-bit integers
*  torch.uint8 : unsigned 8-bit integers
*  torch.int16 or torch.short : signed 16-bit integers
*  torch.int32 or torch.int : signed 32-bit integers
*  torch.int64 or torch.long : signed 64-bit integers
*  torch.bool : Boolean

# passing computations to the GPU and bringing them back to CPU 


## for declairng points on GPU ram itself 
`torch.rand((3,3),device = 'cuda')`

In [17]:
torch.randn((3,3), device = 'cuda')

RuntimeError: ignored

In [18]:
torch.randn((3,3),device = 'cpu')

tensor([[ 1.2566, -0.5868, -2.5443],
        [-1.5580, -0.0174, -1.2153],
        [ 0.4373, -0.4418,  0.2284]])

## for pointing the copy of tensor to GPU 
`tensor.to(device = 'cuda')`


In [19]:
x = torch.rand((3,3))
x 

tensor([[0.7218, 0.3510, 0.8346],
        [0.8031, 0.4956, 0.5727],
        [0.9988, 0.5188, 0.1361]])

In [20]:
x.point(device = 'cuda')

AttributeError: ignored

# numpy exchanges 

In [21]:
x 

tensor([[0.7218, 0.3510, 0.8346],
        [0.8031, 0.4956, 0.5727],
        [0.9988, 0.5188, 0.1361]])

In [22]:
x.numpy()

array([[0.7217749 , 0.35102737, 0.8345992 ],
       [0.8031484 , 0.4956004 , 0.5727415 ],
       [0.99877393, 0.5188257 , 0.13612312]], dtype=float32)

In [23]:
## giving inputs from numpy arrays 

In [31]:
import numpy as np 
np_arr=np.random.rand(3,2)

In [32]:
# converting the above np array to torch tensor 
torch.from_numpy(np_arr)

tensor([[0.4877, 0.7793],
        [0.7493, 0.3300],
        [0.4707, 0.5370]], dtype=torch.float64)

In [33]:
# or we have another one 
torch.tensor(np_arr)

tensor([[0.4877, 0.7793],
        [0.7493, 0.3300],
        [0.4707, 0.5370]], dtype=torch.float64)

# what if we want to save some points to the memory if we want to have weights of that tensors exactly 

In [36]:
torch.save(np_arr,'./out_points.t')

In [38]:
# reading the saved points 
torch.load('./out_points.t')

array([[0.48772983, 0.77927247],
       [0.74926265, 0.33001337],
       [0.47069321, 0.53696633]])

# summary 

*  Neural networks transform floating-point representations into other floating-
point representations. The starting and ending representations are typically
human interpretable, but the intermediate representations are less so.
*  These floating-point representations are stored in tensors.
*  Tensors are multidimensional arrays; they are the basic data structure in
PyTorch.
*  PyTorch has a comprehensive standard library for tensor creation, manipula-
tion, and mathematical operations.
*  Tensors can be serialized to disk and loaded back.
*  All tensor operations in PyTorch can execute on the CPU as well as on the GPU,
with no change in the code.
*  PyTorch uses a trailing underscore to indicate that a function operates in place
on a tensor (for example, Tensor.sqrt_ ).